### ISSUE TITLE
Icons animation on hover new code

### ISSUE THREAD

**Issue by aaossa** [aaossa/aaossa.github.io#20]
Instead of Javascript...

```css
i:hover {
	animation: rotate_and_scale 1s infinite ease-in-out;
}

@keyframes rotate_and_scale {
	0% { transform: rotate(0deg); font-size: 14px; }
	50% { transform: rotate(360deg); font-size: 24px; }
	90% { transform: rotate(360deg); font-size: 24px; }
	100% { transform: rotate(360deg); font-size: 14px; }
}
```

**Comment by aaossa** [comment]
No JavaScript :grin:

**Comment by aaossa** [comment]
If we want a shadow in the animation...

```css
@keyframes rotate_and_scale {
	0% { transform: rotate(0deg); font-size: 20px; text-shadow: 0px 0px 0px #999999; }
	50% { transform: rotate(360deg); font-size: 25px; text-shadow: 3px 3px 3px #999999; }
	90% { transform: rotate(360deg); font-size: 25px; text-shadow: 3px 3px 3px #999999; }
	100% { transform: rotate(360deg); font-size: 20px; text-shadow: 0px 0px 0px #999999; }
}
```
